### ISSUE TITLE
GQL previousPage and nextPage Ordering Returns Different Data Based on Location

### ISSUE THREAD

**Issue by raffik16** [funkhaus/fuxt-backend#14]
Move the queries up
![Screen_Shot_2021-06-03_at_2_05_55_PM](https://user-images.githubusercontent.com/69125695/120712432-777f9600-c475-11eb-9711-0bdfaa2183f8.png)

Move the queries down
![Screen_Shot_2021-06-03_at_2_05_35_PM](https://user-images.githubusercontent.com/69125695/120712398-6cc50100-c475-11eb-917e-ed456cf5ce34.png)

**Comment by rsm0128** [comment]
@raffik16 
I can see the 2nd screenshot returns the wrong data. I tried to replicate the issue, but it's fine for me.
![image](https://user-images.githubusercontent.com/45686588/121914571-58cea880-cd6d-11eb-8873-128bb868e9d6.png)

It would be great if you provide me the access to the site with the error so that I can investigate further in more detail.
Thanks

**Comment by raffik16** [comment]
@rsm0128 This is where I experienced the issue: https://sixtwentysix-api.flywheelsites.com/wp-admin/admin.php?page=graphiql-ide

**Comment by rsm0128** [comment]
@raffik16 
I investigated the issue and found that the issue is already fixed with commit [#3eb30cd](https://github.com/funkhaus/fuxt-backend/commit/3eb30cd2e6cfe1626e95f452f6f80cc471a1726b) on May 6.
The site is using the older version of fuxt-backend and it caused such an issue.

**Comment by rsm0128** [comment]
@raffik16 Have you had chance to test the fix?

**Comment by raffik16** [comment]
@rsm0128 I'm still seeing different being data returning based on the location of the QGL position.
![Screen_Shot_2021-07-06_at_10_00_02_AM](https://user-images.githubusercontent.com/69125695/124639550-27636d00-de41-11eb-96b2-a517e79d3711.png)

**Comment by rsm0128** [comment]
@raffik16  Did you update fuxt-backend to the latest version?

**Comment by raffik16** [comment]
No I have not, I will do that and get back to you.

**Comment by drewbaker** [comment]
Fixed now
